name: env_tutorial

# Triggers the workflow on push or pull_request
on: [pull_request, push]

jobs:
  job1:
    runs-on: ubuntu-latest

    env:
      API_KEY: XXXXXXXXXXXX   # Variable de entorno solo para job1

    steps:
      - name: step 1
        run: echo "The API key is:${{env.API_KEY}}"

  job2:
    runs-on: ubuntu-latest

    steps:
      - name: step 1
        run: echo "The API key is:$API_KEY"
